### ISSUE TITLE
Yaw angle of markers not correct

### ISSUE THREAD

**Issue by sam-melsen** [callemein/ros_robot#1]
The marker detection node outputs an angle (the yaw). This appears to be incorrect. Here is the output of the file raw/markers/distances.txt

foto in.jpg

id: 127
x: 0.174258053303
z: 0.87858080864
yaw: -0.230710819364

id: 128
x: 0.0495527759194
z: 0.91699296236
yaw: 0.0938613861799

id: 129
x: -0.0784552693367
z: 0.903358876705
yaw: -0.150770500302

As you can see, the x-coordinate is positive for ID's 127 and 128, but the yaw is negative for ID 127 and positive for ID 128 which is impossible.

**Comment by BjornVT** [comment]
Fixed the angles. Now trying to get the distance more accurate.

**Comment by BjornVT** [comment]
Calibrated robot camera. The distances are now right. but the angles are off again.

**Comment by BjornVT** [comment]
Fixed. The error now is entirely due to calibration of the camera.
